# Generated by Django 6.0.6 on 2026-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pacote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="Título")),
                ("destino", models.CharField(max_length=100, verbose_name="Destino")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data_saida", models.DateField(verbose_name="Data de Saída")),
                ("data_retorno", models.DateField(verbose_name="Data de Retorno")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "vagas_totais",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Vagas Totais"
                    ),
                ),
                (
                    "vagas_disponiveis",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Vagas Disponíveis"
                    ),
                ),
                ("inclui", models.TextField(blank=True, verbose_name="O que inclui")),
                ("nao_inclui", models.TextField(blank=True, verbose_name="Não inclui")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pacotes/",
                        verbose_name="Imagem",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pacote",
                "verbose_name_plural": "Pacotes",
                "ordering": ["data_saida"],
            },
        ),
    ]
