# Generated by Django 6.0.5 on 2026-05-10 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registro_interno",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Registro Interno"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                ("cargo", models.CharField(max_length=100)),
                ("data_admissao", models.DateField(verbose_name="Data de Admissão")),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "endereco",
                    models.CharField(max_length=255, verbose_name="Endereço Completo"),
                ),
                ("numero", models.CharField(max_length=20, verbose_name="Número")),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                (
                    "banco",
                    models.CharField(max_length=100, verbose_name="Nome do Banco"),
                ),
                ("agencia", models.CharField(max_length=20, verbose_name="Agência")),
                (
                    "conta",
                    models.CharField(max_length=30, verbose_name="Conta com Dígito"),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=150, verbose_name="Título do Documento"
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rh.funcionario"
                    ),
                ),
            ],
        ),
    ]
