# Generated by Django 6.0.5 on 2026-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entregador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                ("telefone", models.CharField(max_length=20)),
                ("cnh", models.CharField(max_length=20, verbose_name="Número da CNH")),
                (
                    "veiculo",
                    models.CharField(
                        max_length=50, verbose_name="Veículo (Ex: Moto, Carro, Van)"
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, verbose_name="Placa do Veículo"),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Está ativo?"),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
