# Generated by Django 6.0.5 on 2026-05-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_entregador"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregador",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fotos_entregadores/",
                verbose_name="Foto",
            ),
        ),
    ]
