# Generated by Django 6.0.6 on 2026-06-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagamentos", "0001_initial"),
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="reserva",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagamentos",
                to="reservas.reserva",
            ),
        ),
    ]
