# Generated by Django 6.0.6 on 2026-06-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0002_initial"),
        ("vendedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="parcelas",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1x"),
                    (2, "2x"),
                    (3, "3x"),
                    (4, "4x"),
                    (5, "5x"),
                    (6, "6x"),
                    (7, "7x"),
                    (8, "8x"),
                    (9, "9x"),
                    (10, "10x"),
                    (11, "11x"),
                    (12, "12x"),
                ],
                default=1,
                null=True,
                verbose_name="Parcelas",
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamentos_recebidos",
                to="vendedores.vendedor",
                verbose_name="Vendedor Responsável",
            ),
        ),
    ]
