# Generated by Django 6.0.6 on 2026-06-15 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0005_pagamento_desconto"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="comprovante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pagamentos/comprovantes/",
                verbose_name="Comprovante",
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data do Pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="forma",
            field=models.CharField(
                choices=[
                    ("pix", "PIX"),
                    ("dinheiro", "Dinheiro"),
                    ("cartao_credito", "Cartão de Crédito"),
                    ("gratuito", "Free"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
