# Generated by Django 6.0.6 on 2026-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_clientes",
            field=models.BooleanField(default=True, verbose_name="Clientes"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_configuracoes",
            field=models.BooleanField(default=False, verbose_name="Configurações"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_pacotes",
            field=models.BooleanField(default=False, verbose_name="Pacotes"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_pagamentos",
            field=models.BooleanField(default=True, verbose_name="Pagamentos"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_relatorios",
            field=models.BooleanField(default=False, verbose_name="Relatórios"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_reservas",
            field=models.BooleanField(default=True, verbose_name="Reservas"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_vendedores",
            field=models.BooleanField(default=False, verbose_name="Vendedores"),
        ),
    ]
