# Generated by Django 6.0.6 on 2026-06-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_perfilusuario_perm_clientes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="perm_cartoes",
            field=models.BooleanField(default=False, verbose_name="Cartões Aprovados"),
        ),
    ]
