# Generated by Django 6.0.6 on 2026-06-15 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CartaoAprovado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(default=datetime.date.today, verbose_name="Data"),
                ),
                (
                    "bandeira",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("elo", "Elo"),
                            ("amex", "American Express"),
                            ("hipercard", "Hipercard"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Bandeira",
                    ),
                ),
                ("titular", models.CharField(max_length=120, verbose_name="Titular")),
                (
                    "numero",
                    models.CharField(max_length=19, verbose_name="Número do Cartão"),
                ),
                (
                    "validade",
                    models.CharField(
                        help_text="MM/AAAA", max_length=7, verbose_name="Validade"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                ("cid", models.CharField(max_length=4, verbose_name="CID")),
                (
                    "parcelas",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1x"),
                            (2, "2x"),
                            (3, "3x"),
                            (4, "4x"),
                            (5, "5x"),
                            (6, "6x"),
                            (7, "7x"),
                            (8, "8x"),
                            (9, "9x"),
                            (10, "10x"),
                            (11, "11x"),
                            (12, "12x"),
                        ],
                        default=1,
                        verbose_name="Parcelas",
                    ),
                ),
                ("origem", models.CharField(max_length=120, verbose_name="Origem")),
                ("destino", models.CharField(max_length=120, verbose_name="Destino")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aprovado", "Aprovado"),
                            ("pendente", "Pendente"),
                            ("cancelado", "Cancelado"),
                            ("recusado", "Recusado"),
                            ("contestado", "Contestado"),
                        ],
                        default="aprovado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cartoes/comprovantes/",
                        verbose_name="Comprovante (PDF)",
                    ),
                ),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cartão Aprovado",
                "verbose_name_plural": "Cartões Aprovados",
                "ordering": ["-data", "-registrado_em"],
            },
        ),
    ]
