# Generated by Django 5.2.14 on 2026-06-15 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbearia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissaoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "master",
                    models.BooleanField(
                        default=False, verbose_name="Master (acesso total)"
                    ),
                ),
                ("agenda", models.BooleanField(default=True, verbose_name="Agenda")),
                (
                    "clientes",
                    models.BooleanField(default=True, verbose_name="Clientes"),
                ),
                (
                    "barbeiros",
                    models.BooleanField(default=True, verbose_name="Barbeiros"),
                ),
                (
                    "servicos",
                    models.BooleanField(default=True, verbose_name="Serviços"),
                ),
                (
                    "financeiro",
                    models.BooleanField(default=False, verbose_name="Financeiro"),
                ),
                ("planos", models.BooleanField(default=False, verbose_name="Planos")),
                (
                    "relatorios",
                    models.BooleanField(default=False, verbose_name="Relatórios"),
                ),
                (
                    "configuracoes",
                    models.BooleanField(default=False, verbose_name="Configurações"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Usuário",
                "verbose_name_plural": "Permissões de Usuários",
            },
        ),
    ]
