# Generated by Django 5.2.14 on 2026-06-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbearia", "0002_permissao_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="lembrete_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="lembrete_enviado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
