# Generated by Django 6.0.6 on 2026-06-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("cpf", "CPF"), ("passaporte", "Passaporte")],
                        default="cpf",
                        max_length=15,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "documento",
                    models.CharField(max_length=20, verbose_name="Número do Documento"),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=80, verbose_name="Cidade"),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
            },
        ),
    ]
