# Generated by Django 6.0.6 on 2026-06-14 20:40

from django.db import migrations, models


def copiar_documentos(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    for c in Cliente.objects.all():
        tipo = getattr(c, 'tipo_documento', 'cpf')
        doc = getattr(c, 'documento', '') or ''
        if tipo == 'passaporte':
            c.passaporte = doc
        else:
            c.cpf = doc
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        # 1. Adiciona novos campos (mantendo os antigos por enquanto)
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="CPF"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="passaporte",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Passaporte"),
        ),
        # 2. Copia os dados existentes
        migrations.RunPython(copiar_documentos, migrations.RunPython.noop),
        # 3. Remove os campos antigos
        migrations.RemoveField(model_name="cliente", name="documento"),
        migrations.RemoveField(model_name="cliente", name="tipo_documento"),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
    ]
