# Generated by Django 6.0.6 on 2026-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_cliente_validade_passaporte"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="clientes/fotos/", verbose_name="Foto"
            ),
        ),
    ]
